services:

  mysql:
    image: mysql:8.4
    container_name: jwt-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt_demo
      MYSQL_USER: jwt_user
      MYSQL_PASSWORD: jwt_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: