spring.application.name=spring-security-jwt-oauth2
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_demo
spring.datasource.username=jwt_user
spring.datasource.password=jwt_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true